"""create run tables

Revision ID: 32df3a503f42
Revises: 32f9658a2097
Create Date: 2026-02-01 09:10:11.217750

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '32df3a503f42'
down_revision: str | None = '32f9658a2097'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
